version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: hfdi-php-custom
    container_name: hfdi-wordpress
    env_file: .env
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    mem_limit: 1024m

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: hfdi-nginx
    ports:
      - "3000:80"
      - "3443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
      - certs_data:/etc/nginx/certs
    depends_on:
      - php
    mem_limit: 1024m

  mysql:
    image: mysql:8.0
    container_name: hfdi-mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: >
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    mem_limit: 1024m

volumes:
  mysql_data:
  certs_data:
